### ISSUE TITLE
TypeError in model.py

### ISSUE THREAD

**Issue by clemacq** [wustl-cig/DeCAF#2]
#### Description
TypeError: Input 'b' of 'MatMul' Op has type float64 that does not match type float32 of argument 'a'.
#### To Reproduce
python main.py --flagfile=.\datasets\Diatom\train_config.txt
#### Files
model.py
line 204: xy_freq = tf.matmul(in_node[:, :2], fourier_mapping)
#### Tasks
add ".astype('float32')" to "fourier_mapping = np.concatenate((s, c), axis=1).T" (line 202)

**Comment by RenHao116** [comment]
Hi @clemacq, I checked this with our machine and did not see the error. I suspect this is an environment problem (see [decaf.yml](https://github.com/wustl-cig/DeCAF/blob/master/decaf.yml)). 

Thanks for raising the issue and providing the fix for others who might have similar problems.
