### ISSUE TITLE
There is no ground-truth of simulated data in the provided datasets

### ISSUE THREAD

**Issue by liuzhen0212** [wustl-cig/DeCAF#3]
Recently I carefully read your paper. It a great work.
However, there is no ground-truth of simulated data in the provided datasets.
**Could you provide the ground-truth of simulated granulocyte cluster ? Thank you.**

**Comment by sunyumark** [comment]
I just checked the data shared in google drive. You are right that it does not contain the ground truth. I will get back to you soon.

**Comment by sunyumark** [comment]
Sorry for the delay. My access to wustl server was deactivated as I have graduated. I managed to get re-establish the access now so the groundtruth will be put online this week.

**Comment by sunyumark** [comment]
Again, sorry for the delay. I just put the data into google drive. I apologize for the inconvenience.

**Comment by liuzhen0212** [comment]
> Again, sorry for the delay. I just put the data into google drive. I apologize for the inconvenience.

Great thanks!
